
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Open_Sans } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import { EdgeStoreProvider } from '@/lib/edgestore';



const font = Open_Sans({ subsets: ['latin'] })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" >
            <body className={font.className}>
                <EdgeStoreProvider>
                    {children}
                </EdgeStoreProvider>
                <Toaster />
            </body>
        </html>
    )
}
