import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Open_Sans } from 'next/font/google'
import { ModalProvider } from '@/components/providers/modal-provider'


const font = Open_Sans({ subsets: ['latin'] })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={font.className}>
        <ModalProvider />
        {children}</body>
    </html>
  )
}
